In [1]:
import pandas as pd

In [25]:
fake_and_real = pd.read_csv('Fake_Real.csv')
test = pd.read_csv('test.tsv',sep='\t')
train =pd.read_csv('train.tsv',sep='\t')
fake1=pd.read_csv('Fake1.csv')
fake2=pd.read_csv('gossipcop_fake.csv')
fake3=pd.read_csv('politifact_fake.csv')
fake4=pd.read_csv('Fake_news_content_detection.csv')
fake5=pd.read_excel("Fake News Stories.xlsx")
true1=pd.read_csv('True1.csv')
true2=pd.read_csv('gossipcop_real.csv')
true3=pd.read_csv('politifact_real.csv')

In [ ]:
print(true1.head())
print(fake1.head())
print(fake2.head())
print(fake3.head())

                                               title  \
0  As U.S. budget fight looms, Republicans flip t...
1  U.S. military to accept transgender recruits o...
2  Senior U.S. Republican senator: 'Let Mr. Muell...
3  FBI Russia probe helped by Australian diplomat...
4  Trump wants Postal Service to charge 'much mor...

                                                text       subject  \
0  WASHINGTON (Reuters) - The head of a conservat...  politicsNews
1  WASHINGTON (Reuters) - Transgender people will...  politicsNews
2  WASHINGTON (Reuters) - The special counsel inv...  politicsNews
3  WASHINGTON (Reuters) - Trump campaign adviser ...  politicsNews
4  SEATTLE/WASHINGTON (Reuters) - President Donal...  politicsNews

                 date
0  December 31, 2017
1  December 29, 2017
2  December 31, 2017
3  December 30, 2017
4  December 29, 2017
                                               title  \
0  As U.S. budget fight looms, Republicans flip t...
1  U.S. military to accept transgender recruits o...
2  Senior U.S. Republican senator: 'Let Mr. Muell...
3  FBI Russia probe helped by Australian diplomat...
4  Trump wants Postal Service to charge 'much mor...

                                                text       subject  \
0  WASHINGTON (Reuters) - The head of a conservat...  politicsNews
1  WASHINGTON (Reuters) - Transgender people will...  politicsNews
2  WASHINGTON (Reuters) - The special counsel inv...  politicsNews
3  WASHINGTON (Reuters) - Trump campaign adviser ...  politicsNews
4  SEATTLE/WASHINGTON (Reuters) - President Donal...  politicsNews

                 date
0  December 31, 2017
1  December 29, 2017
2  December 31, 2017
3  December 30, 2017
4  December 29, 2017
                                               title  \
0   Donald Trump Sends Out Embarrassing New Year’...
1   Drunk Bragging Trump Staffer Started Russian ...
2   Sheriff David Clarke Becomes An Internet Joke...
3   Trump Is So Obsessed He Even Has Obama’s Name...
4   Pope Francis Just Called Out Donald Trump Dur...

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News
1  House Intelligence Committee Chairman Devin Nu...    News
2  On Friday, it was revealed that former Milwauk...    News
3  On Christmas day, Donald Trump announced that ...    News
4  Pope Francis used his annual Christmas Day mes...    News

                date
0  December 31, 2017
1  December 31, 2017
2  December 30, 2017
3  December 29, 2017
4  December 25, 2017
                                               title  \
0   Donald Trump Sends Out Embarrassing New Year’...
1   Drunk Bragging Trump Staffer Started Russian ...
2   Sheriff David Clarke Becomes An Internet Joke...
3   Trump Is So Obsessed He Even Has Obama’s Name...
4   Pope Francis Just Called Out Donald Trump Dur...

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News
1  House Intelligence Committee Chairman Devin Nu...    News
2  On Friday, it was revealed that former Milwauk...    News
3  On Christmas day, Donald Trump announced that ...    News
4  Pope Francis used his annual Christmas Day mes...    News

                date
0  December 31, 2017
1  December 31, 2017
2  December 30, 2017
3  December 29, 2017
4  December 25, 2017
                     id                                           news_url  \
0  gossipcop-2493749932  www.dailymail.co.uk/tvshowbiz/article-5874213/...
1  gossipcop-4580247171  hollywoodlife.com/2018/05/05/paris-jackson-car...
2   gossipcop-941805037  variety.com/2017/biz/news/tax-march-donald-tru...
3  gossipcop-2547891536  www.dailymail.co.uk/femail/article-3499192/Do-...
4  gossipcop-5476631226  variety.com/2018/film/news/list-2018-oscar-nom...

                                               title  \
0  Did Miley Cyrus and Liam Hemsworth secretly ge...
1  Paris Jackson & Cara Delevingne Enjoy Night Ou...
2  Celebrities Join Tax March in Protest of Donal...
3  Cindy Crawford's daughter Kaia Gerber wears a ...
4      Full List of 2018 Oscar Nominations – Variety

                                           tweet_ids
0  284329075902926848\t284332744559968256\t284335...
1  992895508267130880\t992897935418503169\t992899...
2  853359353532829696\t853359576543920128\t853359...
3  988821905196158981\t988824206556172288\t988825...
4  955792793632432131\t955795063925301249\t955798...
                id                                           news_url  \
0  politifact15014          speedtalk.com/forum/viewtopic.php?t=51650
1  politifact15156  politics2020.info/index.php/2018/03/13/court-o...
2  politifact14745  www.nscdscamps.org/blog/category/parenting/467...
3  politifact14355  https://howafrica.com/oscar-pistorius-attempts...
4  politifact15371  http://washingtonsources.org/trump-votes-for-d...

                                               title  \
0  BREAKING: First NFL Team Declares Bankruptcy O...
1  Court Orders Obama To Pay $400 Million In Rest...
2  UPDATE: Second Roy Moore Accuser Works For Mic...
3         Oscar Pistorius Attempts To Commit Suicide
4        Trump Votes For Death Penalty For Being Gay

                                           tweet_ids
0  937349434668498944\t937379378006282240\t937380...
1  972666281441878016\t972678396575559680\t972827...
2  929405740732870656\t929439450400264192\t929439...
3  886941526458347521\t887011300278194176\t887023...
4  915205698212040704\t915242076681506816\t915249...

In [4]:
true1.tail()

,title,text,subject,date
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017"
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017"
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017"
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017"
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017"

In [32]:
true1.isnull().sum()

title      0
text       0
subject    0
date       0
dtype: int64

In [35]:
df1 = true1['title']
df1[1]

'U.S. military to accept transgender recruits on Monday: Pentagon'

In [ ]:

df1=pd.DataFrame(df1)

In [45]:
df1['Label']= 'True'
df1

                                                   title Label
0      As U.S. budget fight looms, Republicans flip t...  True
1      U.S. military to accept transgender recruits o...  True
2      Senior U.S. Republican senator: 'Let Mr. Muell...  True
3      FBI Russia probe helped by Australian diplomat...  True
4      Trump wants Postal Service to charge 'much mor...  True
...                                                  ...   ...
21413  LexisNexis withdrew two products from Chinese ...  True
21414  Minsk cultural hub becomes haven from authorities  True
21415  Vatican upbeat on possibility of Pope Francis ...  True
21416  Indonesia to buy $1.14 billion worth of Russia...  True
Label                                               True  True

[21418 rows x 2 columns]

In [7]:
fake1.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [46]:
df2= fake1['title']
df2=pd.DataFrame(df2)
df2['Label'] = 'Fake'
df2.head()

                                               title Label
0   Donald Trump Sends Out Embarrassing New Year’...  Fake
1   Drunk Bragging Trump Staffer Started Russian ...  Fake
2   Sheriff David Clarke Becomes An Internet Joke...  Fake
3   Trump Is So Obsessed He Even Has Obama’s Name...  Fake
4   Pope Francis Just Called Out Donald Trump Dur...  Fake

In [8]:
fake2.head()

,id,news_url,title,tweet_ids
0,gossipcop-2493749932,www.dailymail.co.uk/tvshowbiz/article-5874213/...,Did Miley Cyrus and Liam Hemsworth secretly ge...,284329075902926848\t284332744559968256\t284335...
1,gossipcop-4580247171,hollywoodlife.com/2018/05/05/paris-jackson-car...,Paris Jackson & Cara Delevingne Enjoy Night Ou...,992895508267130880\t992897935418503169\t992899...
2,gossipcop-941805037,variety.com/2017/biz/news/tax-march-donald-tru...,Celebrities Join Tax March in Protest of Donal...,853359353532829696\t853359576543920128\t853359...
3,gossipcop-2547891536,www.dailymail.co.uk/femail/article-3499192/Do-...,Cindy Crawford's daughter Kaia Gerber wears a ...,988821905196158981\t988824206556172288\t988825...
4,gossipcop-5476631226,variety.com/2018/film/news/list-2018-oscar-nom...,Full List of 2018 Oscar Nominations – Variety,955792793632432131\t955795063925301249\t955798...

In [47]:
df3=fake2['title']
df3=pd.DataFrame(df3)
df3['Label']= 'Fake'
df3.head()

                                               title Label
0  Did Miley Cyrus and Liam Hemsworth secretly ge...  Fake
1  Paris Jackson & Cara Delevingne Enjoy Night Ou...  Fake
2  Celebrities Join Tax March in Protest of Donal...  Fake
3  Cindy Crawford's daughter Kaia Gerber wears a ...  Fake
4      Full List of 2018 Oscar Nominations – Variety  Fake

In [9]:
fake3.head()

,id,news_url,title,tweet_ids
0,politifact15014,speedtalk.com/forum/viewtopic.php?t=51650,BREAKING: First NFL Team Declares Bankruptcy O...,937349434668498944\t937379378006282240\t937380...
1,politifact15156,politics2020.info/index.php/2018/03/13/court-o...,Court Orders Obama To Pay $400 Million In Rest...,972666281441878016\t972678396575559680\t972827...
2,politifact14745,www.nscdscamps.org/blog/category/parenting/467...,UPDATE: Second Roy Moore Accuser Works For Mic...,929405740732870656\t929439450400264192\t929439...
3,politifact14355,https://howafrica.com/oscar-pistorius-attempts...,Oscar Pistorius Attempts To Commit Suicide,886941526458347521\t887011300278194176\t887023...
4,politifact15371,http://washingtonsources.org/trump-votes-for-d...,Trump Votes For Death Penalty For Being Gay,915205698212040704\t915242076681506816\t915249...

In [48]:
df4 = fake3['title']
df4=pd.DataFrame(df4)
df4['Label']='Fake'
df4.head()

                                               title Label
0  BREAKING: First NFL Team Declares Bankruptcy O...  Fake
1  Court Orders Obama To Pay $400 Million In Rest...  Fake
2  UPDATE: Second Roy Moore Accuser Works For Mic...  Fake
3         Oscar Pistorius Attempts To Commit Suicide  Fake
4        Trump Votes For Death Penalty For Being Gay  Fake

In [10]:
train.head()

,2635.json,false,Says the Annies List political group supports third-trimester abortions on demand.,abortion,dwayne-bohac,State representative,Texas,republican,0,1,0.1,0.2,0.3,a mailer
0,10540.json,half-true,When did the decline of coal start? It started...,"energy,history,job-accomplishments",scott-surovell,State delegate,Virginia,democrat,0.0,0.0,1.0,1.0,0.0,a floor speech.
1,324.json,mostly-true,"Hillary Clinton agrees with John McCain ""by vo...",foreign-policy,barack-obama,President,Illinois,democrat,70.0,71.0,160.0,163.0,9.0,Denver
2,1123.json,false,Health care reform legislation is likely to ma...,health-care,blog-posting,NaN,NaN,none,7.0,19.0,3.0,5.0,44.0,a news release
3,9028.json,half-true,The economic turnaround started at the end of ...,"economy,jobs",charlie-crist,NaN,Florida,democrat,15.0,9.0,20.0,19.0,2.0,an interview on CNN
4,12465.json,true,The Chicago Bears have had more starting quart...,education,robin-vos,Wisconsin Assembly speaker,Wisconsin,republican,0.0,3.0,2.0,5.0,1.0,a an online opinion-piece

In [12]:
test.head()

,11972.json,true,Building a wall on the U.S.-Mexico border will take literally years.,immigration,rick-perry,Governor,Texas,republican,30,30.1,42,23,18,Radio interview
0,11685.json,false,Wisconsin is on pace to double the number of l...,jobs,katrina-shankland,State representative,Wisconsin,democrat,2,1,0,0,0,a news conference
1,11096.json,false,Says John McCain has done nothing to help the ...,"military,veterans,voting-record",donald-trump,President-Elect,New York,republican,63,114,51,37,61,comments on ABC's This Week.
2,5209.json,half-true,Suzanne Bonamici supports a plan that will cut...,"medicare,message-machine-2012,campaign-adverti...",rob-cornilles,consultant,Oregon,republican,1,1,3,1,1,a radio show
3,9524.json,pants-fire,When asked by a reporter whether hes at the ce...,"campaign-finance,legal-issues,campaign-adverti...",state-democratic-party-wisconsin,NaN,Wisconsin,democrat,5,7,2,2,7,a web video
4,5962.json,true,Over the past five years the federal governmen...,"federal-budget,pensions,retirement",brendan-doherty,NaN,Rhode Island,republican,1,2,1,1,0,a campaign website

In [ ]:
train.columns = [
"id","label","statement","subject","speaker","speaker_job_title",
"state_info","party_affiliation","barely_true_counts","false_counts",
"half_true_counts","mostly_true_counts","pants_on_fire_counts","context"
]

train.head()

,id,label,statement,subject,speaker,speaker_job_title,state_info,party_affiliation,barely_true_counts,false_counts,half_true_counts,mostly_true_counts,pants_on_fire_counts,context
0,10540.json,half-true,When did the decline of coal start? It started...,"energy,history,job-accomplishments",scott-surovell,State delegate,Virginia,democrat,0.0,0.0,1.0,1.0,0.0,a floor speech.
1,324.json,mostly-true,"Hillary Clinton agrees with John McCain ""by vo...",foreign-policy,barack-obama,President,Illinois,democrat,70.0,71.0,160.0,163.0,9.0,Denver
2,1123.json,false,Health care reform legislation is likely to ma...,health-care,blog-posting,NaN,NaN,none,7.0,19.0,3.0,5.0,44.0,a news release
3,9028.json,half-true,The economic turnaround started at the end of ...,"economy,jobs",charlie-crist,NaN,Florida,democrat,15.0,9.0,20.0,19.0,2.0,an interview on CNN
4,12465.json,true,The Chicago Bears have had more starting quart...,education,robin-vos,Wisconsin Assembly speaker,Wisconsin,republican,0.0,3.0,2.0,5.0,1.0,a an online opinion-piece

In [56]:
train['label'].unique()

array(['half-true', 'mostly-true', 'false', 'true', 'barely-true',
       'pants-fire'], dtype=object)

In [61]:
df5 = train[['statement','label']]
df5 = pd.DataFrame(df5)
df5.head()

                                           statement        label
0  When did the decline of coal start? It started...    half-true
1  Hillary Clinton agrees with John McCain "by vo...  mostly-true
2  Health care reform legislation is likely to ma...        false
3  The economic turnaround started at the end of ...    half-true
4  The Chicago Bears have had more starting quart...         true

In [63]:
df5 = df5.rename(columns={'statement':'title'})
df5.head()

                                               title        label
0  When did the decline of coal start? It started...    half-true
1  Hillary Clinton agrees with John McCain "by vo...  mostly-true
2  Health care reform legislation is likely to ma...        false
3  The economic turnaround started at the end of ...    half-true
4  The Chicago Bears have had more starting quart...         true

In [64]:
df5['label'] = df5['label'].replace({
    "half-true":'True',
    "mostly-true":"True",
    "true":"True",
    "pants-fire":"False",
    "false":"False",
    "barely-true":"False"
})

In [65]:
df5['label'].unique()

array(['True', 'False'], dtype=object)

In [66]:
df5.head()

                                               title  label
0  When did the decline of coal start? It started...   True
1  Hillary Clinton agrees with John McCain "by vo...   True
2  Health care reform legislation is likely to ma...  False
3  The economic turnaround started at the end of ...   True
4  The Chicago Bears have had more starting quart...   True

In [67]:
test.columns = [
"id","label","statement","subject","speaker","speaker_job_title",
"state_info","party_affiliation","barely_true_counts","false_counts",
"half_true_counts","mostly_true_counts","pants_on_fire_counts","context"
]

test.head()

,id,label,statement,subject,speaker,speaker_job_title,state_info,party_affiliation,barely_true_counts,false_counts,half_true_counts,mostly_true_counts,pants_on_fire_counts,context
0,11685.json,false,Wisconsin is on pace to double the number of l...,jobs,katrina-shankland,State representative,Wisconsin,democrat,2,1,0,0,0,a news conference
1,11096.json,false,Says John McCain has done nothing to help the ...,"military,veterans,voting-record",donald-trump,President-Elect,New York,republican,63,114,51,37,61,comments on ABC's This Week.
2,5209.json,half-true,Suzanne Bonamici supports a plan that will cut...,"medicare,message-machine-2012,campaign-adverti...",rob-cornilles,consultant,Oregon,republican,1,1,3,1,1,a radio show
3,9524.json,pants-fire,When asked by a reporter whether hes at the ce...,"campaign-finance,legal-issues,campaign-adverti...",state-democratic-party-wisconsin,NaN,Wisconsin,democrat,5,7,2,2,7,a web video
4,5962.json,true,Over the past five years the federal governmen...,"federal-budget,pensions,retirement",brendan-doherty,NaN,Rhode Island,republican,1,2,1,1,0,a campaign website

In [69]:
df6 = test[['statement','label']]
df6= pd.DataFrame(df6)
df6.head()

                                           statement       label
0  Wisconsin is on pace to double the number of l...       false
1  Says John McCain has done nothing to help the ...       false
2  Suzanne Bonamici supports a plan that will cut...   half-true
3  When asked by a reporter whether hes at the ce...  pants-fire
4  Over the past five years the federal governmen...        true

In [72]:
df6['label'] = df6['label'].replace({
    "half-true":'True',
    "mostly-true":"True",
    "true":"True",
    "pants-fire":"False",
    "false":"False",
    "barely-true":"False"
})

df6 = df6.rename(columns={'statement':'title'})
df6.head()

                                               title  label
0  Wisconsin is on pace to double the number of l...  False
1  Says John McCain has done nothing to help the ...  False
2  Suzanne Bonamici supports a plan that will cut...   True
3  When asked by a reporter whether hes at the ce...  False
4  Over the past five years the federal governmen...   True

In [26]:
true2.head()

,id,news_url,title,tweet_ids
0,gossipcop-882573,https://www.brides.com/story/teen-mom-jenelle-...,Teen Mom Star Jenelle Evans' Wedding Dress Is ...,912371411146149888\t912371528343408641\t912372...
1,gossipcop-875924,https://www.dailymail.co.uk/tvshowbiz/article-...,Kylie Jenner refusing to discuss Tyga on Life ...,901989917546426369\t901989992074969089\t901990...
2,gossipcop-894416,https://en.wikipedia.org/wiki/Quinn_Perkins,Quinn Perkins,931263637246881792\t931265332022579201\t931265...
3,gossipcop-857248,https://www.refinery29.com/en-us/2018/03/19192...,I Tried Kim Kardashian's Butt Workout & Am For...,868114761723936769\t868122567910936576\t868128...
4,gossipcop-884684,https://www.cnn.com/2017/10/04/entertainment/c...,Celine Dion donates concert proceeds to Vegas ...,915528047004209152\t915529285171122176\t915530...

In [75]:
df7 = true2['title']
df7 = pd.DataFrame(df7)
df7['label']= 'True'
df7.head()

                                               title label
0  Teen Mom Star Jenelle Evans' Wedding Dress Is ...  True
1  Kylie Jenner refusing to discuss Tyga on Life ...  True
2                                      Quinn Perkins  True
3  I Tried Kim Kardashian's Butt Workout & Am For...  True
4  Celine Dion donates concert proceeds to Vegas ...  True

In [27]:
true3.head()

,id,news_url,title,tweet_ids
0,politifact14984,http://www.nfib-sbet.org/,National Federation of Independent Business,967132259869487105\t967164368768196609\t967215...
1,politifact12944,http://www.cq.com/doc/newsmakertranscripts-494...,comments in Fayetteville NC,942953459\t8980098198\t16253717352\t1668513250...
2,politifact333,https://web.archive.org/web/20080204072132/htt...,"Romney makes pitch, hoping to close deal : Ele...",NaN
3,politifact4358,https://web.archive.org/web/20110811143753/htt...,Democratic Leaders Say House Democrats Are Uni...,NaN
4,politifact779,https://web.archive.org/web/20070820164107/htt...,"Budget of the United States Government, FY 2008",89804710374154240\t91270460595109888\t96039619...

In [76]:
df8 = true3['title']
df8 = pd.DataFrame(df8)
df8['label']= 'True'
df8.head()

                                               title label
0        National Federation of Independent Business  True
1                        comments in Fayetteville NC  True
2  Romney makes pitch, hoping to close deal : Ele...  True
3  Democratic Leaders Say House Democrats Are Uni...  True
4    Budget of the United States Government, FY 2008  True

In [28]:
fake3.head()

,id,news_url,title,tweet_ids
0,politifact15014,speedtalk.com/forum/viewtopic.php?t=51650,BREAKING: First NFL Team Declares Bankruptcy O...,937349434668498944\t937379378006282240\t937380...
1,politifact15156,politics2020.info/index.php/2018/03/13/court-o...,Court Orders Obama To Pay $400 Million In Rest...,972666281441878016\t972678396575559680\t972827...
2,politifact14745,www.nscdscamps.org/blog/category/parenting/467...,UPDATE: Second Roy Moore Accuser Works For Mic...,929405740732870656\t929439450400264192\t929439...
3,politifact14355,https://howafrica.com/oscar-pistorius-attempts...,Oscar Pistorius Attempts To Commit Suicide,886941526458347521\t887011300278194176\t887023...
4,politifact15371,http://washingtonsources.org/trump-votes-for-d...,Trump Votes For Death Penalty For Being Gay,915205698212040704\t915242076681506816\t915249...

In [77]:
df9 = fake3['title']
df9 = pd.DataFrame(df9)
df9['label']= 'Fake'
df9.head()

                                               title label
0  BREAKING: First NFL Team Declares Bankruptcy O...  Fake
1  Court Orders Obama To Pay $400 Million In Rest...  Fake
2  UPDATE: Second Roy Moore Accuser Works For Mic...  Fake
3         Oscar Pistorius Attempts To Commit Suicide  Fake
4        Trump Votes For Death Penalty For Being Gay  Fake

In [29]:
fake4.head()

,Unnamed: 0,Text,Text_Tag,Barely-True,False,Half-True,Mostly-True,Not-Known,True
0,0,Says the Annies List political group supports ...,abortion,0,1,0,0,0,0
1,1,When did the decline of coal start? It started...,"energy,history,job-accomplishments",0,0,1,0,0,0
2,2,"Hillary Clinton agrees with John McCain ""by vo...",foreign-policy,0,0,0,1,0,0
3,3,Health care reform legislation is likely to ma...,health-care,0,1,0,0,0,0
4,4,The economic turnaround started at the end of ...,"economy,jobs",0,0,1,0,0,0

In [82]:
df10 = fake4['Text']
df10= pd.DataFrame(df10)

In [83]:
df10 = df10.rename(columns={'Text':'title'})

In [90]:
df10['label'] = fake4.apply(lambda x:"True" if (x["True"]==1 or x['Mostly-True']==1) else "Fake",axis=1)
df10.head()

                                               title label
0  Says the Annies List political group supports ...  Fake
1  When did the decline of coal start? It started...  Fake
2  Hillary Clinton agrees with John McCain "by vo...  True
3  Health care reform legislation is likely to ma...  Fake
4  The economic turnaround started at the end of ...  Fake

In [91]:
df10['label'].unique()

array(['Fake', 'True'], dtype=object)

In [30]:
fake5.head()

,Article Number,URL of article,Fake or Satire?,URL of rebutting article,Fake or Satire?.1
0,375,http://www.redflagnews.com/headlines-2016/cdc-...,Fake,http://www.snopes.com/cdc-forced-vaccinations/,Fake
1,376,http://www.redflagnews.com/headlines-2016/-out...,Fake,http://www.snopes.com/white-house-logo-change/,Fake
2,377,http://www.redflagnews.com/headlines-2016/whit...,Fake,http://www.snopes.com/obama-veterans-money-to-...,Fake
3,378,http://www.redflagnews.com/headlines-2016/obam...,Fake,http://www.snopes.com/obama-veterans-money-to-...,Fake
4,379,http://www.redflagnews.com/headlines-2016/cali...,Fake,http://www.snopes.com/california-to-jail-clima...,Fake

In [96]:
fake5['Fake or Satire?'].unique()

array(['Fake', 'Satire', 'Satire '], dtype=object)

In [17]:
test.to_csv('test.csv')
train.to_csv('train.csv')

In [18]:
fake_and_real = pd.read_csv('Fake_Real.csv')

In [19]:
fake_and_real.head()

,Unnamed: 0,text,subject,target
0,0,new york reuters us environmental group sierra...,politicsNews,True
1,1,washington reuters us air force asked industry...,politicsNews,True
2,2,saturday paul ryan posted photo instagram phot...,News,Fake
3,3,america keeps waiting word hillary indicted ob...,politics,Fake
4,4,religion peace ht weasel zippers,left-news,Fake

In [102]:
df11 = fake_and_real[['text','target']]
df11.head()

                                                text target
0  new york reuters us environmental group sierra...   True
1  washington reuters us air force asked industry...   True
2  saturday paul ryan posted photo instagram phot...   Fake
3  america keeps waiting word hillary indicted ob...   Fake
4                   religion peace ht weasel zippers   Fake

In [104]:
df11 = df11.rename(columns={'text':'title','target':'label'})
df11

                                                   title label
0      new york reuters us environmental group sierra...  True
1      washington reuters us air force asked industry...  True
2      saturday paul ryan posted photo instagram phot...  Fake
3      america keeps waiting word hillary indicted ob...  Fake
4                       religion peace ht weasel zippers  Fake
...                                                  ...   ...
44893  new york reuters myanmar national security adv...  True
44894  reckless hillary cared less seriousness exposi...  Fake
44895  montevideo reuters lucia topolansky uruguay se...  True
44896  donald trump getting heavy media coverage late...  Fake
44897  jakarta reuters indonesian security forces eas...  True

[44898 rows x 2 columns]

In [21]:
fake4 = pd.read_csv('Fake_news_content_detection.csv')
fake4

,Unnamed: 0,Text,Text_Tag,Barely-True,False,Half-True,Mostly-True,Not-Known,True
0,0,Says the Annies List political group supports ...,abortion,0,1,0,0,0,0
1,1,When did the decline of coal start? It started...,"energy,history,job-accomplishments",0,0,1,0,0,0
2,2,"Hillary Clinton agrees with John McCain ""by vo...",foreign-policy,0,0,0,1,0,0
3,3,Health care reform legislation is likely to ma...,health-care,0,1,0,0,0,0
4,4,The economic turnaround started at the end of ...,"economy,jobs",0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...
10235,10235,There are a larger number of shark attacks in ...,"animals,elections",0,0,0,1,0,0
10236,10236,Democrats have now become the party of the [At...,elections,0,0,0,1,0,0
10237,10237,Says an alternative to Social Security that op...,"retirement,social-security",0,0,1,0,0,0
10238,10238,On lifting the U.S. Cuban embargo and allowing...,"florida,foreign-policy",0,1,0,0,0,0
10239,10239,The Department of Veterans Affairs has a manua...,"health-care,veterans",0,0,0,0,1,0

In [105]:
df1.head()

                                               title Label
0  As U.S. budget fight looms, Republicans flip t...  True
1  U.S. military to accept transgender recruits o...  True
2  Senior U.S. Republican senator: 'Let Mr. Muell...  True
3  FBI Russia probe helped by Australian diplomat...  True
4  Trump wants Postal Service to charge 'much mor...  True

In [107]:
df2.head()

                                               title Label
0   Donald Trump Sends Out Embarrassing New Year’...  Fake
1   Drunk Bragging Trump Staffer Started Russian ...  Fake
2   Sheriff David Clarke Becomes An Internet Joke...  Fake
3   Trump Is So Obsessed He Even Has Obama’s Name...  Fake
4   Pope Francis Just Called Out Donald Trump Dur...  Fake

In [108]:
df3.head()

                                               title Label
0  Did Miley Cyrus and Liam Hemsworth secretly ge...  Fake
1  Paris Jackson & Cara Delevingne Enjoy Night Ou...  Fake
2  Celebrities Join Tax March in Protest of Donal...  Fake
3  Cindy Crawford's daughter Kaia Gerber wears a ...  Fake
4      Full List of 2018 Oscar Nominations – Variety  Fake

In [109]:
df4.head()

                                               title Label
0  BREAKING: First NFL Team Declares Bankruptcy O...  Fake
1  Court Orders Obama To Pay $400 Million In Rest...  Fake
2  UPDATE: Second Roy Moore Accuser Works For Mic...  Fake
3         Oscar Pistorius Attempts To Commit Suicide  Fake
4        Trump Votes For Death Penalty For Being Gay  Fake

In [118]:
df4=df4.rename(columns={'Label':'label'})

In [119]:
df4.head()

                                               title label
0  BREAKING: First NFL Team Declares Bankruptcy O...  Fake
1  Court Orders Obama To Pay $400 Million In Rest...  Fake
2  UPDATE: Second Roy Moore Accuser Works For Mic...  Fake
3         Oscar Pistorius Attempts To Commit Suicide  Fake
4        Trump Votes For Death Penalty For Being Gay  Fake

In [121]:
df4=df4.rename(columns={'label':'Label'})

In [110]:
df5.head()

                                               title  label
0  When did the decline of coal start? It started...   True
1  Hillary Clinton agrees with John McCain "by vo...   True
2  Health care reform legislation is likely to ma...  False
3  The economic turnaround started at the end of ...   True
4  The Chicago Bears have had more starting quart...   True

In [122]:
df5=df5.rename(columns={'label':'Label'})

In [111]:
df6.head()

                                               title  label
0  Wisconsin is on pace to double the number of l...  False
1  Says John McCain has done nothing to help the ...  False
2  Suzanne Bonamici supports a plan that will cut...   True
3  When asked by a reporter whether hes at the ce...  False
4  Over the past five years the federal governmen...   True

In [123]:
df6=df6.rename(columns={'label':'Label'})

In [112]:
df7.head()

                                               title label
0  Teen Mom Star Jenelle Evans' Wedding Dress Is ...  True
1  Kylie Jenner refusing to discuss Tyga on Life ...  True
2                                      Quinn Perkins  True
3  I Tried Kim Kardashian's Butt Workout & Am For...  True
4  Celine Dion donates concert proceeds to Vegas ...  True

In [124]:
df7=df7.rename(columns={'label':'Label'})

In [113]:
df8.head()

                                               title label
0        National Federation of Independent Business  True
1                        comments in Fayetteville NC  True
2  Romney makes pitch, hoping to close deal : Ele...  True
3  Democratic Leaders Say House Democrats Are Uni...  True
4    Budget of the United States Government, FY 2008  True

In [125]:
df8=df8.rename(columns={'label':'Label'})

In [114]:
df9.head()

                                               title label
0  BREAKING: First NFL Team Declares Bankruptcy O...  Fake
1  Court Orders Obama To Pay $400 Million In Rest...  Fake
2  UPDATE: Second Roy Moore Accuser Works For Mic...  Fake
3         Oscar Pistorius Attempts To Commit Suicide  Fake
4        Trump Votes For Death Penalty For Being Gay  Fake

In [126]:
df9=df9.rename(columns={'label':'Label'})

In [115]:
df10.head()

                                               title label
0  Says the Annies List political group supports ...  Fake
1  When did the decline of coal start? It started...  Fake
2  Hillary Clinton agrees with John McCain "by vo...  True
3  Health care reform legislation is likely to ma...  Fake
4  The economic turnaround started at the end of ...  Fake

In [127]:
df10=df10.rename(columns={'label':'Label'})

In [116]:
df11.head()

                                               title label
0  new york reuters us environmental group sierra...  True
1  washington reuters us air force asked industry...  True
2  saturday paul ryan posted photo instagram phot...  Fake
3  america keeps waiting word hillary indicted ob...  Fake
4                   religion peace ht weasel zippers  Fake

In [128]:
df11=df11.rename(columns={'label':'Label'})

In [196]:
combined_df = pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11])
combined_df.head()

                                               title Label
0  As U.S. budget fight looms, Republicans flip t...  True
1  U.S. military to accept transgender recruits o...  True
2  Senior U.S. Republican senator: 'Let Mr. Muell...  True
3  FBI Russia probe helped by Australian diplomat...  True
4  Trump wants Postal Service to charge 'much mor...  True

In [197]:
combined_df.tail()

                                                   title Label
44893  new york reuters myanmar national security adv...  True
44894  reckless hillary cared less seriousness exposi...  Fake
44895  montevideo reuters lucia topolansky uruguay se...  True
44896  donald trump getting heavy media coverage late...  Fake
44897  jakarta reuters indonesian security forces eas...  True

In [131]:
combined_df.to_csv('data.csv')

In [132]:
combined_df['Label'].unique()

array(['True', 'Fake', 'False'], dtype=object)

In [203]:
combined_df['Label']=combined_df['Label'].replace({
    'False':'Fake'
})
combined_df.tail()

                                                   title Label
44893  new york reuters myanmar national security adv...  True
44894  reckless hillary cared less seriousness exposi...  Fake
44895  montevideo reuters lucia topolansky uruguay se...  True
44896  donald trump getting heavy media coverage late...  Fake
44897  jakarta reuters indonesian security forces eas...  True

In [204]:
combined_df.head()

                                               title Label
0  As U.S. budget fight looms, Republicans flip t...  True
1  U.S. military to accept transgender recruits o...  True
2  Senior U.S. Republican senator: 'Let Mr. Muell...  True
3  FBI Russia probe helped by Australian diplomat...  True
4  Trump wants Postal Service to charge 'much mor...  True

In [205]:
combined_df['Label'].unique()

array(['True', 'Fake'], dtype=object)

In [206]:
combined_df.head()

                                               title Label
0  As U.S. budget fight looms, Republicans flip t...  True
1  U.S. military to accept transgender recruits o...  True
2  Senior U.S. Republican senator: 'Let Mr. Muell...  True
3  FBI Russia probe helped by Australian diplomat...  True
4  Trump wants Postal Service to charge 'much mor...  True

In [207]:
df12=pd.read_csv('covidSelfDataset.csv')

In [208]:
df12.head()

                                                text outcome
0  A post claims compulsory vacination violates t...    fake
1  A photo claims that this person is a doctor wh...    fake
2  Post about a video claims that it is a protest...    fake
3  All deaths by respiratory failure and pneumoni...    fake
4  The dean of the College of Biologists of Euska...    fake

In [209]:
df12 = df12.rename(columns={'text':'title','outcome':'Label'})
df12.tail()

                                                   title Label
16984  Fishing industry in Windsor-Essex shut down du...  real
16985   Health Canada worker tests positive for COVID-19  real
16986  Taxis adapting to COVID-19 with plastic shield...  real
16987  'An amazing man': Young father identified as n...  real
16988  N.S. municipality warns against annual Easter ...  real

In [210]:
combined_df.head()

                                               title Label
0  As U.S. budget fight looms, Republicans flip t...  True
1  U.S. military to accept transgender recruits o...  True
2  Senior U.S. Republican senator: 'Let Mr. Muell...  True
3  FBI Russia probe helped by Australian diplomat...  True
4  Trump wants Postal Service to charge 'much mor...  True

In [202]:
combined_df.tail()

                                                   title Label
44893  new york reuters myanmar national security adv...  True
44894  reckless hillary cared less seriousness exposi...  Fake
44895  montevideo reuters lucia topolansky uruguay se...  True
44896  donald trump getting heavy media coverage late...  Fake
44897  jakarta reuters indonesian security forces eas...  True

In [212]:
combined_df = pd.concat([combined_df,df12],ignore_index=True)
combined_df.tail()

                                                    title Label
169143  Fishing industry in Windsor-Essex shut down du...  real
169144   Health Canada worker tests positive for COVID-19  real
169145  Taxis adapting to COVID-19 with plastic shield...  real
169146  'An amazing man': Young father identified as n...  real
169147  N.S. municipality warns against annual Easter ...  real

In [213]:
combined_df.tail()

                                                    title Label
169143  Fishing industry in Windsor-Essex shut down du...  real
169144   Health Canada worker tests positive for COVID-19  real
169145  Taxis adapting to COVID-19 with plastic shield...  real
169146  'An amazing man': Young father identified as n...  real
169147  N.S. municipality warns against annual Easter ...  real

In [214]:
combined_df['Label'].value_counts()

Label
True    70379
Fake    64791
fake    19454
real    14524
Name: count, dtype: int64

In [215]:
combined_df['Label'] = combined_df['Label'].replace({
    'fake':'Fake',
    'False':'Fake',
    'real':'True',
})
combined_df.head()

                                               title Label
0  As U.S. budget fight looms, Republicans flip t...  True
1  U.S. military to accept transgender recruits o...  True
2  Senior U.S. Republican senator: 'Let Mr. Muell...  True
3  FBI Russia probe helped by Australian diplomat...  True
4  Trump wants Postal Service to charge 'much mor...  True

In [216]:
combined_df['Label'].value_counts()

Label
True    84903
Fake    84245
Name: count, dtype: int64

In [183]:
data1 = pd.read_csv('Fake_Real_News_Data.csv')
data1.tail()

,Unnamed: 0,title,text,label
6330,6330,Obama To Limit Police Acquisition Of Some Mili...,Obama To Limit Police Acquisition Of Some Mili...,REAL
6331,6331,EU using taxpayer money to give Muslim invader...,BNI Store Oct 29 2016 EU using taxpayer money ...,FAKE
6332,6332,Watching These 55 ISIS Terrorists Get Blown to...,Next Story → Judge Judy LOSES IT on Hood Rat: ...,FAKE
6333,6333,America’s Streets Will Run With Blood- Mike Adams,America’s Streets Will Run With Blood- Mike Ad...,FAKE
6334,6334,The immigration swamp,“This was not a subject that was on anybody’s ...,REAL

In [217]:
df13 = data1[['title','label']]
df13=pd.DataFrame(df13)
df13.head()

                                               title label
0  A whirlwind day in D.C. showcases Trump’s unor...  REAL
1  In Baltimore's call for federal police probe, ...  REAL
2  Trump Proudly Declares: Most Of The People I’v...  FAKE
3  Inside the Trump-Bush melodrama: Decades of te...  REAL
4      Shutdown clash to return in force by December  REAL

In [218]:
df13 = df13.rename(columns={'label':'Label'})

In [219]:
df13.head()

                                               title Label
0  A whirlwind day in D.C. showcases Trump’s unor...  REAL
1  In Baltimore's call for federal police probe, ...  REAL
2  Trump Proudly Declares: Most Of The People I’v...  FAKE
3  Inside the Trump-Bush melodrama: Decades of te...  REAL
4      Shutdown clash to return in force by December  REAL

In [220]:
df13['Label']= df13['Label'].replace({
    'REAL':'True',
    'FAKE':'Fake'
})

In [221]:
df13['Label'].unique()

array(['True', 'Fake'], dtype=object)

In [222]:
combined_df = pd.concat([df13,combined_df],ignore_index=True)

In [223]:
combined_df.tail()

                                                    title Label
175478  Fishing industry in Windsor-Essex shut down du...  True
175479   Health Canada worker tests positive for COVID-19  True
175480  Taxis adapting to COVID-19 with plastic shield...  True
175481  'An amazing man': Young father identified as n...  True
175482  N.S. municipality warns against annual Easter ...  True

In [224]:
df14 = data1[['text','label']]
df14=pd.DataFrame(df14)

df14.head()

                                                text label
0  Donald Trump endorsed an unabashedly noninterv...  REAL
1  While some Justice Department investigations a...  REAL
2  Trump Proudly Declares: Most Of The People I’v...  FAKE
3  Donald Trump spent a day in January 2014 hobno...  REAL
4  Notable names include Ray Washburne (Commerce)...  REAL

In [225]:
df14 = df14.rename(columns={'label':'Label','text':'title'})

In [227]:
df14['Label']= df14['Label'].replace({
    'REAL':'True',
    'FAKE':'Fake'
})
df14.head()

                                               title Label
0  Donald Trump endorsed an unabashedly noninterv...  True
1  While some Justice Department investigations a...  True
2  Trump Proudly Declares: Most Of The People I’v...  Fake
3  Donald Trump spent a day in January 2014 hobno...  True
4  Notable names include Ray Washburne (Commerce)...  True

In [228]:
combined_df = pd.concat([df14,combined_df],ignore_index=True)
combined_df.tail()

                                                    title Label
181813  Fishing industry in Windsor-Essex shut down du...  True
181814   Health Canada worker tests positive for COVID-19  True
181815  Taxis adapting to COVID-19 with plastic shield...  True
181816  'An amazing man': Young father identified as n...  True
181817  N.S. municipality warns against annual Easter ...  True

In [230]:
combined_df.drop_duplicates(inplace=True)

In [236]:
combined_df.duplicated().sum()

0

In [238]:
combined_df = combined_df.reset_index(drop=True)
combined_df.tail()

                                                    title Label
139085  Seniors staying positive through COVID-19 pand...  True
139086   Health Canada worker tests positive for COVID-19  True
139087  Taxis adapting to COVID-19 with plastic shield...  True
139088  'An amazing man': Young father identified as n...  True
139089  N.S. municipality warns against annual Easter ...  True

In [240]:
combined_df['Label'].value_counts()

Label
True    76593
Fake    62497
Name: count, dtype: int64

In [242]:
combined_df.to_csv('final.csv')